version: '3.9'

services:
  java_db:
    container_name: form_builder_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kzi219430@
      POSTGRES_DB: form_builder
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}